### ISSUE TITLE
error when wrong option is passed

### ISSUE THREAD

**Issue by retokromer** [MediaArea/MOVMetaEdit#36]
When passing a dadaist option I got:

<img width="810" alt="bildschirmfoto 2018-08-17 um 18 44 45" src="https://user-images.githubusercontent.com/3246607/44278363-0fbd1980-a24e-11e8-9183-4dfba442314b.png">

I suggest to:
- better align the text to 80 chars (I could open a PR for this)
- exit with an error state, not with an OK state.

**Comment by JeromeMartinez** [comment]
> better align the text to 80 chars (I could open a PR for this)

I don't have strong feelings about it, up to you.

> exit with an error state, not with an OK state.

It was definitely not a priority from the sponsor, but I [improved it a bit](https://github.com/MediaArea/MOVMetaEdit/pull/37).
Not willing to go a lot further about that as adding code is always risky, and it is maybe not worth to take the risk to break something especially because for the moment there is no active sponsor for this project (so nobody for sponsoring such kind of fixes + the fix of the buggy fix+ adding more regression tests).

**Comment by retokromer** [comment]
>I don't have strong feelings about it, up to you.

@JeromeMartinez Do you know from the top of your head where the code is? Otherwise I will search for it.

**Comment by JeromeMartinez** [comment]
https://github.com/MediaArea/MOVMetaEdit/blob/master/Source/movedit_main.cpp#L196

**Comment by retokromer** [comment]
Thank you! I will give a try and open a PR during the weekend.

**Comment by retokromer** [comment]
FYI: I just noticed that «Dada» also occurs for `movmetaedit --version`. I suggest either to simply delete that option from the help message: 

<img width="808" alt="bildschirmfoto 2018-08-18 um 11 42 28" src="https://user-images.githubusercontent.com/3246607/44298023-d59a5900-a2db-11e8-9a3c-bfb920b2a1f4.png">

or (preferred) to implement that option.

**Comment by JeromeMartinez** [comment]
> I just noticed that «Dada» also occurs for `movmetaedit --version` [...] or (preferred) to implement that option.

Update pushed to the PR.
